# Generated by Django 4.0.3 on 2022-04-06 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='password',
        ),
    ]
