# Generated by Django 4.0.3 on 2022-04-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eauth', '0003_signup_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
